version: "3.8"

services:
  gmod:
    image: ceifa/garrysmod:latest
    container_name: gmod_ttt
    ports:
      - "27015:27015/udp"
      - "27015:27015/tcp"
    environment:
      GAMEMODE: "terrortown"
      MAP: "ttt_minecraft_b5"
      MAXPLAYERS: "20"
      HOSTNAME: "Flexii’s TTT Server"
      WORKSHOPCOLLECTIONID: "852620310"
      WORKSHOP_AUTHKEY: "${WORKSHOP_AUTHKEY}"
      PRODUCTION: "1"
    volumes:
      - ./garrysmod:/home/gmod/server/garrysmod
